# Generated by Django 5.2.6 on 2025-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_last_4', models.CharField(db_index=True, help_text='Last 4 digits of Aadhaar for display purposes', max_length=4)),
                ('aadhaar_hash', models.CharField(help_text='Hash of full Aadhaar number for verification', max_length=64, unique=True)),
                ('full_name', models.CharField(help_text='Name as per Aadhaar', max_length=100)),
                ('date_of_birth', models.DateField(help_text='DOB as per Aadhaar (YYYY-MM-DD)')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender as per Aadhaar', max_length=1)),
                ('address_line', models.TextField(help_text='Address as per Aadhaar')),
                ('pin_code', models.CharField(help_text='PIN code as per Aadhaar', max_length=6)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to disable this Aadhaar record')),
                ('created_by', models.CharField(default='admin', help_text='Admin user who created this record', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aadhaar Record',
                'verbose_name_plural': 'Aadhaar Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PANRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_last_4', models.CharField(db_index=True, help_text='Last 4 characters of PAN for display', max_length=5)),
                ('pan_hash', models.CharField(help_text='Hash of full PAN for verification', max_length=64, unique=True)),
                ('full_name', models.CharField(help_text='Name as per PAN', max_length=100)),
                ('date_of_birth', models.DateField(help_text='DOB as per PAN (YYYY-MM-DD)')),
                ('father_name', models.CharField(blank=True, help_text="Father's name as per PAN", max_length=100)),
                ('pan_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled')], default='active', help_text='PAN status as per IT Department', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to disable this PAN record')),
                ('created_by', models.CharField(default='admin', help_text='Admin user who created this record', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PAN Record',
                'verbose_name_plural': 'PAN Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
