# Generated by Django 5.2.6 on 2025-09-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_aadhaarrecord_panrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_attempts',
            field=models.IntegerField(default=0, help_text='Number of failed PIN attempts (for security)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_hash',
            field=models.CharField(blank=True, help_text='Hashed 6-digit PIN for secure login (never store plain PIN)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, help_text='PIN locked until this time (if too many failed attempts)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pin_set_at',
            field=models.DateTimeField(blank=True, help_text='When the PIN was last set or updated', null=True),
        ),
    ]
