# Generated by Django 5.2.6 on 2025-10-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('current_step', models.IntegerField(default=1)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('mobile_otp', models.CharField(blank=True, max_length=6)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('current_address', models.TextField(blank=True)),
                ('aadhaar_otp', models.CharField(blank=True, max_length=6)),
                ('aadhaar_verified', models.BooleanField(default=False)),
                ('aadhaar_verified_at', models.DateTimeField(blank=True, null=True)),
                ('aadhaar_name', models.CharField(blank=True, max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('pan_otp', models.CharField(blank=True, max_length=6)),
                ('pan_verified', models.BooleanField(default=False)),
                ('pan_verified_at', models.DateTimeField(blank=True, null=True)),
                ('pan_name', models.CharField(blank=True, max_length=100)),
                ('pin', models.CharField(blank=True, max_length=6)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'signup_progress',
                'ordering': ['-created_at'],
            },
        ),
    ]
