# Generated by Django 5.2.6 on 2025-11-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='customer_id',
            field=models.IntegerField(blank=True, editable=False, help_text='5-digit unique customer identifier', null=True, unique=True),
        ),
    ]
